/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_dkp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class asisten extends javax.swing.JFrame {
    
    private String nama;
    private int Umur;
    private String Kelamin;
    private String Alamat;
    private int Hp;
    private String Pekerjaan;
    private int i=1;

    /**
     * Creates new form asisten
     */
    public asisten() {
        initComponents();
        String []book={"Hari","Napas Pendek","Demam","Batuk","Menggigil dan Pegal pegal","Pilek","Masalah Pencernaan",
            "Mata Merah Muda","Kehilangan Bau dan Rasa","Kelelahan","Sakit Kepala, Sakit Tenggorokan, Hidung Tersumbat","Kebingungan Mendadak"};
        DefaultTableModel model = new DefaultTableModel(book,0);
        tblHasil.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasil = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tvPekerjaan = new javax.swing.JLabel();
        tvHp = new javax.swing.JLabel();
        tvAlamat = new javax.swing.JLabel();
        tvKelamin = new javax.swing.JLabel();
        tvUmur = new javax.swing.JLabel();
        tvNama = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        y10 = new javax.swing.JRadioButton();
        t10 = new javax.swing.JRadioButton();
        t11 = new javax.swing.JRadioButton();
        y11 = new javax.swing.JRadioButton();
        t9 = new javax.swing.JRadioButton();
        y9 = new javax.swing.JRadioButton();
        t8 = new javax.swing.JRadioButton();
        y8 = new javax.swing.JRadioButton();
        t7 = new javax.swing.JRadioButton();
        y7 = new javax.swing.JRadioButton();
        y6 = new javax.swing.JRadioButton();
        t6 = new javax.swing.JRadioButton();
        y5 = new javax.swing.JRadioButton();
        t5 = new javax.swing.JRadioButton();
        y4 = new javax.swing.JRadioButton();
        t4 = new javax.swing.JRadioButton();
        y3 = new javax.swing.JRadioButton();
        t3 = new javax.swing.JRadioButton();
        t2 = new javax.swing.JRadioButton();
        y2 = new javax.swing.JRadioButton();
        t1 = new javax.swing.JRadioButton();
        y1 = new javax.swing.JRadioButton();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHasil);

        jLabel1.setText("Nama");

        jLabel2.setText("Umur");

        jLabel3.setText("Kelamin");

        jLabel4.setText("Alamat");

        jLabel5.setText("Nomor Hp");

        jLabel6.setText("Pekerjaan");

        tvPekerjaan.setText("jLabel7");

        tvHp.setText("jLabel8");

        tvAlamat.setText("jLabel9");

        tvKelamin.setText("jLabel10");

        tvUmur.setText("jLabel11");

        tvNama.setText("jLabel12");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("FORM GEJALA");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Napas Pendek");

        jLabel15.setText("Demam");

        jLabel16.setText("Batuk");

        jLabel17.setText("Menggigil dan Pegal pegal");

        jLabel18.setText("Pilek");

        jLabel19.setText("Masalah Pencernaan");

        jLabel20.setText("Mata Merah Muda");

        jLabel21.setText("Kehilangan Bau dan Rasa");

        jLabel22.setText("Kelelahan");

        jLabel23.setText("Sakit Kepala, Sakit Tenggorokan,");

        jLabel24.setText("Hidung Tersumbat");

        jLabel25.setText("Kebingungan Mendadak");

        y10.setText("Ya");
        y10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y10ActionPerformed(evt);
            }
        });

        t10.setText("Tidak");
        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });

        t11.setText("Tidak");
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });

        y11.setText("Ya");
        y11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y11ActionPerformed(evt);
            }
        });

        t9.setText("Tidak");
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });

        y9.setText("Ya");
        y9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y9ActionPerformed(evt);
            }
        });

        t8.setText("Tidak");
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });

        y8.setText("Ya");
        y8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y8ActionPerformed(evt);
            }
        });

        t7.setText("Tidak");
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        y7.setText("Ya");
        y7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y7ActionPerformed(evt);
            }
        });

        y6.setText("Ya");
        y6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y6ActionPerformed(evt);
            }
        });

        t6.setText("Tidak");
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        y5.setText("Ya");
        y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y5ActionPerformed(evt);
            }
        });

        t5.setText("Tidak");
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        y4.setText("Ya");
        y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y4ActionPerformed(evt);
            }
        });

        t4.setText("Tidak");
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        y3.setText("Ya");
        y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3ActionPerformed(evt);
            }
        });

        t3.setText("Tidak");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t2.setText("Tidak");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        y2.setText("Ya");
        y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2ActionPerformed(evt);
            }
        });

        t1.setText("Tidak");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        y1.setText("Ya");
        y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(jLabel25)
                                .addComponent(jLabel22)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19)
                                .addComponent(jLabel18)
                                .addComponent(jLabel17))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y4)
                                    .addGap(18, 18, 18)
                                    .addComponent(t4))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y5)
                                    .addGap(18, 18, 18)
                                    .addComponent(t5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y6)
                                    .addGap(18, 18, 18)
                                    .addComponent(t6))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y7)
                                    .addGap(18, 18, 18)
                                    .addComponent(t7))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y8)
                                    .addGap(18, 18, 18)
                                    .addComponent(t8))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y9)
                                    .addGap(18, 18, 18)
                                    .addComponent(t9))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y11)
                                    .addGap(18, 18, 18)
                                    .addComponent(t11))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y10)
                                    .addGap(18, 18, 18)
                                    .addComponent(t10))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y2)
                                    .addGap(18, 18, 18)
                                    .addComponent(t2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y3)
                                    .addGap(18, 18, 18)
                                    .addComponent(t3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(y1)
                                    .addGap(18, 18, 18)
                                    .addComponent(t1)))))
                    .addComponent(jLabel24))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(y1)
                    .addComponent(t1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(y2)
                    .addComponent(t2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(y3)
                    .addComponent(t3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(y4)
                    .addComponent(t4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(y5)
                    .addComponent(t5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(y6)
                    .addComponent(t6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(y7)
                    .addComponent(t7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(y8)
                    .addComponent(t8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(y9)
                    .addComponent(t9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(y10)
                        .addComponent(t10)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(y11)
                    .addComponent(t11))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKembali.setText("Keluar");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tvAlamat))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tvHp))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(tvPekerjaan)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tvNama)
                                            .addComponent(tvUmur)
                                            .addComponent(tvKelamin))))
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnReset)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSimpan)))
                                .addGap(41, 41, 41)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 192, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tvNama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tvUmur))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tvKelamin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tvAlamat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tvHp))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tvPekerjaan))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnReset))
                        .addGap(18, 18, 18)
                        .addComponent(btnKembali)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1ActionPerformed
        // TODO add your handling code here:
        if(y1.isSelected()){
            t1.setSelected(false);
        }
    }//GEN-LAST:event_y1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        if(t1.isSelected()){
            y1.setSelected(false);
        }
    }//GEN-LAST:event_t1ActionPerformed

    private void y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2ActionPerformed
        // TODO add your handling code here:
        if(y2.isSelected()){
            t2.setSelected(false);
        }
    }//GEN-LAST:event_y2ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
        if(t2.isSelected()){
            y2.setSelected(false);
        }
    }//GEN-LAST:event_t2ActionPerformed

    private void y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3ActionPerformed
        // TODO add your handling code here:
        if(y3.isSelected()){
            t3.setSelected(false);
        }
    }//GEN-LAST:event_y3ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
        if(t3.isSelected()){
            y3.setSelected(false);
        }
    }//GEN-LAST:event_t3ActionPerformed

    private void y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y4ActionPerformed
        // TODO add your handling code here:
        if(y4.isSelected()){
            t4.setSelected(false);
        }
    }//GEN-LAST:event_y4ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
        if(t4.isSelected()){
            y4.setSelected(false);
        }
    }//GEN-LAST:event_t4ActionPerformed

    private void y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y5ActionPerformed
        // TODO add your handling code here:
        if(y5.isSelected()){
            t5.setSelected(false);
        }
    }//GEN-LAST:event_y5ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
        if(t5.isSelected()){
            y5.setSelected(false);
        }
    }//GEN-LAST:event_t5ActionPerformed

    private void y6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y6ActionPerformed
        // TODO add your handling code here:
        if(y6.isSelected()){
            t6.setSelected(false);
        }
    }//GEN-LAST:event_y6ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
        if(t6.isSelected()){
            y6.setSelected(false);
        }
    }//GEN-LAST:event_t6ActionPerformed

    private void y7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y7ActionPerformed
        // TODO add your handling code here:
        if(y7.isSelected()){
            t7.setSelected(false);
        }
    }//GEN-LAST:event_y7ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
        if(t7.isSelected()){
            y7.setSelected(false);
        }
    }//GEN-LAST:event_t7ActionPerformed

    private void y8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y8ActionPerformed
        // TODO add your handling code here:
        if(y8.isSelected()){
            t8.setSelected(false);
        }
    }//GEN-LAST:event_y8ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
        if(t8.isSelected()){
            y8.setSelected(false);
        }
    }//GEN-LAST:event_t8ActionPerformed

    private void y9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y9ActionPerformed
        // TODO add your handling code here:
        if(y9.isSelected()){
            t9.setSelected(false);
        }
    }//GEN-LAST:event_y9ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
        if(t9.isSelected()){
            y9.setSelected(false);
        }
    }//GEN-LAST:event_t9ActionPerformed

    private void y10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y10ActionPerformed
        // TODO add your handling code here:
        if(y10.isSelected()){
            t10.setSelected(false);
        }
    }//GEN-LAST:event_y10ActionPerformed

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
        // TODO add your handling code here:
        if(t10.isSelected()){
            y10.setSelected(false);
        }
    }//GEN-LAST:event_t10ActionPerformed

    private void y11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y11ActionPerformed
        // TODO add your handling code here:
        if(y11.isSelected()){
            t11.setSelected(false);
        }
    }//GEN-LAST:event_y11ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
        if(t11.isSelected()){
            y11.setSelected(false);
        }
    }//GEN-LAST:event_t11ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String p1 = "-" ,p2 = "-" ,p3 = "-",p4 = "-",p5 = "-",p6 = "-",p7 = "-",p8 = "-",p9 = "-",p10 = "-",p11 = "-";
        
        if(y1.isSelected()){
            p1 = "Ya";
        } else if (t1.isSelected()){
            p1 = "Tidak";
        }
        
        if(y2.isSelected()){
            p2 = "Ya";
        } else if (t2.isSelected()){
            p2 = "Tidak";
        }
        
        if(y3.isSelected()){
            p3 = "Ya";
        } else if (t3.isSelected()){
            p3 = "Tidak";
        }
        
        if(y4.isSelected()){
            p4 = "Ya";
        } else if (t4.isSelected()){
            p4 = "Tidak";
        }
        
        if(y5.isSelected()){
            p5 = "Ya";
        } else if (t5.isSelected()){
            p5 = "Tidak";
        }
        
        if(y6.isSelected()){
            p6 = "Ya";
        } else if (t6.isSelected()){
            p6 = "Tidak";
        }
        
        if(y7.isSelected()){
            p7 = "Ya";
        } else if (t7.isSelected()){
            p7 = "Tidak";
        }
        
        if(y8.isSelected()){
            p8 = "Ya";
        } else if (t8.isSelected()){
            p8 = "Tidak";
        }
        
        if(y9.isSelected()){
            p9 = "Ya";
        } else if (t9.isSelected()){
            p9 = "Tidak";
        }
        
        if(y10.isSelected()){
            p10 = "Ya";
        } else if (t10.isSelected()){
            p10 = "Tidak";
        }
        
        if(y11.isSelected()){
            p11 = "Ya";
        } else if (t11.isSelected()){
            p11 = "Tidak";
        }
        
        if(p1 == "-" || p2=="-" || p3 == "-" || p4 == "-" || p5 == "-" || p6 == "-" || p7 == "-" || p8 == "-" || p9 == "-" || p10 == "-" || p11 == "-"){
           JOptionPane.showMessageDialog(null, "Ada kolom yang belum terisi!"); 
        } else {
            DefaultTableModel model = (DefaultTableModel) tblHasil.getModel();
            model.addRow(new Object[]{i,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11});
            this.i++;
            setClear();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Ingin mereset kolom ?", 
                    "Reset", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
            reset();
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Keluar memnyebabkan kolom hilang, setuju ?", 
                    "Keluar", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
    
        if(jawab == JOptionPane.YES_OPTION){
            this.setVisible(false);
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asisten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asisten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asisten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asisten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asisten().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton t1;
    private javax.swing.JRadioButton t10;
    private javax.swing.JRadioButton t11;
    private javax.swing.JRadioButton t2;
    private javax.swing.JRadioButton t3;
    private javax.swing.JRadioButton t4;
    private javax.swing.JRadioButton t5;
    private javax.swing.JRadioButton t6;
    private javax.swing.JRadioButton t7;
    private javax.swing.JRadioButton t8;
    private javax.swing.JRadioButton t9;
    private javax.swing.JTable tblHasil;
    private javax.swing.JLabel tvAlamat;
    private javax.swing.JLabel tvHp;
    private javax.swing.JLabel tvKelamin;
    private javax.swing.JLabel tvNama;
    private javax.swing.JLabel tvPekerjaan;
    private javax.swing.JLabel tvUmur;
    private javax.swing.JRadioButton y1;
    private javax.swing.JRadioButton y10;
    private javax.swing.JRadioButton y11;
    private javax.swing.JRadioButton y2;
    private javax.swing.JRadioButton y3;
    private javax.swing.JRadioButton y4;
    private javax.swing.JRadioButton y5;
    private javax.swing.JRadioButton y6;
    private javax.swing.JRadioButton y7;
    private javax.swing.JRadioButton y8;
    private javax.swing.JRadioButton y9;
    // End of variables declaration//GEN-END:variables

    public void setEt(String nama, int umur, String kelamin, String alamat, int hp, String pekerjaan){
        this.nama=nama;
        this.Umur=umur;
        this.Kelamin=kelamin;
        this.Alamat=alamat;
        this.Hp=hp;
        this.Pekerjaan=pekerjaan;
        
        tvNama.setText(this.nama);
        tvUmur.setText(String.valueOf(this.Umur));
        tvKelamin.setText(this.Kelamin);
        tvAlamat.setText(this.Alamat);
        tvHp.setText(String.valueOf(this.Hp));
        tvPekerjaan.setText(this.Pekerjaan);
    }
    
    private void setClear(){
        y1.setSelected(false);
        y2.setSelected(false);
        y3.setSelected(false);
        y4.setSelected(false);
        y5.setSelected(false);
        y6.setSelected(false);
        y7.setSelected(false);
        y8.setSelected(false);
        y9.setSelected(false);
        y10.setSelected(false);
        y11.setSelected(false);
        
        t1.setSelected(false);
        t2.setSelected(false);
        t3.setSelected(false);
        t4.setSelected(false);
        t5.setSelected(false);
        t6.setSelected(false);
        t7.setSelected(false);
        t8.setSelected(false);
        t9.setSelected(false);
        t10.setSelected(false);
        t11.setSelected(false);
    }
    
    private void reset(){
        DefaultTableModel model = (DefaultTableModel) tblHasil.getModel();
        int row = model.getRowCount();
        for(int i=row-1;i>=0;i--){           
            model.removeRow(i);
        };
    }
    
}
